system:
  timezone: Europe/Bratislava
  card_enabled: true
  cal_enabled: true
  invite_from: ""
  dav_auth_type: Basic
  admin_passwordhash: d033e22ae348aeb5660fc2140aec35850c4da997

database:
  mysql: false
  mysql_host: ~
  mysql_dbname: ~
  mysql_username: ~
  mysql_password: ~
  sqlite_file: Specific/db/db.sqlite
  encryption_key: ""
