homeassistant:
  enabled: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto:1883
  keepalive: 60
  reject_unauthorized: true
  version: 4
serial:
  port: /dev/ttyACM0
  disable_led: false
advanced:
  log_level: info
  log_directory: /app/data/log/%TIMESTAMP%
  log_file: log.txt
  log_rotation: true
  log_symlink_current: true
  pan_id: 60951
  network_key:
    - 32
    - 9
    - 12
    - 17
    - 185
    - 93
    - 67
    - 88
    - 181
    - 232
    - 131
    - 18
    - 133
    - 47
    - 32
    - 53
  channel: 11
  frontend:
    port: 8080
    host: 0.0.0.0
  ota_disable_automatic_update_check: false
device_options:
  retain: true
  optimistic: true
devices: {}
groups: {}
version: 4
